# Generated by Django 3.0.8 on 2020-09-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('otp', models.CharField(max_length=4)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='otp',
        ),
    ]
